spring:
  application:
    name: eureka-server

server:
  port: 7000
  tomcat:
    uri-encoding: UTF-8

eureka:
  server:
    enable-self-preservation: false
  instance:
    instance-id: localhost:${spring.application.name}:${server.port}
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/