#服务提供者的运行端口
server:
  port: 7100
  tomcat:
    uri-encoding: UTF-8

#服务提供者的应用名称，http://localhost:7000/页面当中会显示出来
spring:
  application:
    name: study-gateway
  #用户配置开发(dev)，测试(test)，生产(prod)的配置文件，避免频繁改动
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:7000/eureka/
  instance:
    prefer-ip-address: true




