server:
  port: 7300 #端口
  tomcat:
    uri-encoding: utf-8
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/if341886/study.git #git配置
          search-paths: properties #搜索目录
          username: 290341886@qq.com #账号
          password: cheng341886 #密码

  application:
    name: study-config #服务名
  #用户配置开发(dev)，测试(test)，生产(prod)的配置文件，避免频繁改动
  profiles:
    active: dev


eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:7000/eureka/ #eureka注册地址
  instance:
    prefer-ip-address: true # Ip地址注册
